### ISSUE TITLE
Update pycairo

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-forge/pycairo-feedstock#1] opened 2017-06-21 14:59 UTC
Hello,

I am trying to add [PyGObject](https://pygobject.readthedocs.io) to `conda-forge`, and it requires `pycairo>=1.11.1`. However, the latest version of this package in `conda-forge` is 1.11.0.

Could you please update pycairo to its latest version?
https://github.com/pygobject/pycairo/releases

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment] 2017-06-21 16:24
pinging @pkgw

**Comment by pkgw** [comment] 2017-06-21 16:40
I've tried updating to 1.13.3 in #2. It might take a few tries to get things working since it looks like the package's build system is a bit of a moving target.

**Comment by sebastian-luna-valero** [comment] 2017-06-21 17:43
Thanks for trying!

**Comment by lazka** [comment] 2017-06-21 18:10
Short summary of what has changed with pycairo since 1.11:

* Previously pycairo was split in a Python 2 and 3 version in different repos with different build systems. Since 1.11 they got merged back into one source and can be build for both Python versions.
* It previously used waf or autotools as a build system, now it just uses distutils like commonly used by other python packages (setup.py build/install)
* I don't expect any of this to change again in the future.
* The new versions are API/ABI backwards compatible with 1.10

If there are any questions, please ask here or open an issue at https://github.com/pygobject/pycairo

**Comment by pkgw** [comment] 2017-06-21 18:44
@lazka Yeah, sorry for the imprecision — I don't mean the build system per se, but for instance our package carries some patches to build in our Windows environment, and based on the release notes it looks like some of the code in the `setup.py` has been evolving. For instance, based on the CI results it does look like our Windows patch needs updating.

**Comment by lazka** [comment] 2017-06-21 19:00
@pkgw ah, sorry, I missed that you already use the new build system. Yeah, the c99 patch can be dropped as that's fixed the the new releases (and tested in CI). The other patch needs to be refreshed I guess. It looks conda specific, but if you have any pointers on how other packages handle library discovery without pkg-config I can try to integrate that upstream. I'm only using msys2/mingw atm to build on Windows where pkg-config happens to be available.

**Comment by sebastian-luna-valero** [comment] 2017-06-22 07:32
Many thanks both!

**Comment by pkgw** [comment] 2017-06-22 12:28
CI tests passed so I've merged the PR; new version should roll out over the course of today or so.

@lazka I have no idea what I'm doing with the Windows stuff so I don't feel very qualified to give any advice. Our builds are also based on msys2/mingw, but if I recall correctly the problem is that our Windows Cairo package doesn't provide pkg-config files. That may be also true of some of the other dependencies of this package.

**Closed as completed by pkgw** 2017-06-22 12:28 UTC

**Comment by lazka** [comment] 2017-06-22 12:56
Thanks!
